WebApplication1/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApplication1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication1/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Security.Claims;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using JWT.Algorithms;
using JWT.Builder;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace WebApplication1.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly string _token = GenerateAccessToken();
        public IList<Label> labels = new List<Label>();
        public IList<Package> packages = new List<Package>();
        private readonly string webserver = "https://warm-castle-36416.herokuapp.com";
        private readonly IHttpClientFactory _clientFactory;
        public IndexModel(ILogger<IndexModel> logger, IHttpClientFactory clientFactory)
        {
            _logger = logger;
            _logger.LogInformation(_token);
            _clientFactory = clientFactory;
            labels = GetLabels();
            packages = GetPackages();
        }

        public IActionResult OnPostCreate(string label, string user)
        {
            var request = new HttpRequestMessage(HttpMethod.Post,
                $"{webserver}/courier/packages/{label}?user={user}");

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", _token);

            var response = client.SendAsync(request).Result;
            if (!response.IsSuccessStatusCode)
            {
                throw new HttpRequestException("cannot connect to server");
            }

            return RedirectToPage("Index");
        }

        public IActionResult OnPostChangeStatus(string label, string user)
        {
            var newStatus = Request.Form["newstaus"].ToString();
            var url = $"{webserver}/courier/packages/{label}?state={newStatus}&user={user}";
            var request = new HttpRequestMessage(HttpMethod.Put, url);

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", _token);

            var response = client.SendAsync(request).Result;
            if (!response.IsSuccessStatusCode)
            {
                throw new HttpRequestException("cannot connect to server");
            }

            return RedirectToPage("Index");
        }

        public IList<Label> GetLabels()
        {
            var request = new HttpRequestMessage(HttpMethod.Get,
                $"{webserver}/courier/labels");

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", _token);

            var response = client.SendAsync(request).Result;
            if (response.IsSuccessStatusCode)
            {
                var content = response.Content.ReadAsStringAsync().Result;
                JObject Jcontent = JObject.Parse(content);
                IList<JToken> Jlabs = Jcontent["_embedded"]["items"].ToList();

                IList<Label> list = new List<Label>();
                foreach (JToken result in Jlabs)
                {
                    Label lab = result.ToObject<Label>();
                    list.Add(lab);
                }

                return list;
            }
            throw new HttpRequestException("cannot connect to server");
        }
        public IList<Package> GetPackages()
        {
            var request = new HttpRequestMessage(HttpMethod.Get,
                $"{webserver}/courier/packages");

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Authorization =
                new AuthenticationHeaderValue("Bearer", _token);

            var response = client.SendAsync(request).Result;
            if (response.IsSuccessStatusCode)
            {
                var content = response.Content.ReadAsStringAsync().Result;
                JObject Jcontent = JObject.Parse(content);
                IList<JToken> Jlabs = Jcontent["_embedded"]["items"].ToList();

                IList<Package> list = new List<Package>();
                foreach (JToken result in Jlabs)
                {
                    Package lab = result.ToObject<Package>();
                    list.Add(lab);
                }

                return list;
            }
            throw new HttpRequestException("cannot connect to server");
        }

        private static string GenerateAccessToken()
        {
            return new JwtBuilder()
                .WithAlgorithm(new HMACSHA256Algorithm())
                .WithSecret(Encoding.ASCII.GetBytes("DF8WT34^$SF1Gh%^T@$1"))
                .AddClaim("exp", DateTimeOffset.UtcNow.AddHours(2).ToUnixTimeSeconds())
                .AddClaim("usr", "user")
                .AddClaim("user_role", "courier")
                .AddClaim("aud", "aud")
                .Encode();
        }
    }
}

WebApplication1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Labels</h1>



    <table class="table">
        <thead>
        <tr>
            <th>Label</th>
            <th>Status</th>
            <th>User</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.labels)
        {
            <tr>
                <td>
                    @item.label
                </td>
                <td>
                    @item.status
                </td>
                <td>
                    @item.user
                </td>
                <td>
                    <form asp-page-handler="create" method="post">
                        <button>Create Package</button>
                        <input type="hidden" name="label" value=@item.label />
                        <input type="hidden" name="user" value=@item.user />
                    </form>
                </td>
            </tr>
        }
        </tbody>
    </table>
    <h1 class="display-4">Packages</h1>
    <table class="table">
        <thead>
        <tr>
            <th>Label</th>
            <th>Status</th>
            <th>User</th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model.packages)
        {
            <tr>
                <td>
                    @item.label
                </td>
                <td>
                    @item.status
                </td>
                <td>
                    @item.user
                </td>
                <td>
                    <form asp-page-handler= "changeStatus" method="post">
                        <fieldset>Zmień status 
                            <select  id="newStatus" name="newstaus">
                                <option value="w drodze">w drodze</option>
                                <option value="dostarczona">dostarczona</option>
                                <option value="odebrana">odebrana</option>
                            </select>
                            <button><input type="submit" value="Submit"  /> </button>
                            <input type="hidden" name="label" value=@item.label />
                            <input type="hidden" name="user" value=@item.user />
                        </fieldset>
                    </form>



                </td>
            </tr>
        }
        </tbody>
    </table>

</div>

WebApplication1/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Courier App </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">Courier App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Courier App
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>